// Storage of Arith Level 1 Problems
const problemSet = [
  { problem: '🐻 + 🐻🐻 =', answer: 3 },
  { problem: '🐻🐻 + 🐻🐻🐻 =', answer: 5 },
  { problem: '🐻🐻🐻 + 🐻🐻🐻🐻 =', answer: 7 },
  { problem: '🐼 + 🐼 =', answer: 2 },
  { problem: '🐼🐼 + 🐼🐼 =', answer: 4 },
  { problem: '🐼🐼🐼 + 🐼🐼🐼 =', answer: 6 },
  { problem: '🐢 + 🐢 + 🐢 =', answer: 3 },
  { problem: '🐢 + 🐢🐢 + 🐢 =', answer: 4 },
  { problem: '🐢 + 🐢🐢🐢 + 🐢 =', answer: 5 },
  { problem: '🐌 + 🐌 + 🐌 + 🐌 =', answer: 4 },
  { problem: '🐝🐝 + 🐝🐝 =', answer: 4 },
  { problem: '🐵🐵🐵🐵 + 🐵🐵🐵 =', answer: 7 },
  { problem: '🐵🐵🐵 + 🐵🐵🐵 =', answer: 6 },
  { problem: '🐳  + 🐳  + 🐳 =', answer: 3 },
  { problem: '🌚 + 🌚 =', answer: 2 },
  { problem: '🌙 + 🌙 + 🌙 =', answer: 3 },
  { problem: '🌠🌠🌠 + 🌠🌠🌠 =', answer: 6 },
  { problem: '🌞🌞🌞🌞 + 🌞 =', answer: 5 },
  { problem: '🌌 + 🌌🌌 + 🌌 =', answer: 4 },
  { problem: '🌌 + 🌌🌌🌌 + 🌌 =', answer: 5 },
  { problem: '🪐🪐 + 🪐🪐 + 🪐', answer: 5 },
  { problem: '🌝 + 🌝 + 🌝 =', answer: 3 },
  { problem: '🌟🌟 + 🌟🌟🌟 =', answer: 5 },
  { problem: '🌛🌛  + 🌛🌛 =', answer: 4 },
  { problem: '🌖 + 🌖 + 🌖🌖 =', answer: 4 },
  { problem: '🌘 + 🌘 + 🌘 =', answer: 3 },
  { problem: '🛸🛸 + 🛸🛸 + 🛸 =', answer: 5 },
  { problem: '🛸 + 🛸🛸 + 🛸 =', answer: 4 },
  { problem: '🛸🛸 + 🛸🛸🛸🛸 =', answer: 6 },
  { problem: '👨‍🚀 + 👨‍🚀 =', answer: 2 },
  { problem: '👨‍🚀👨‍🚀 + 👨‍🚀👨‍🚀 =', answer: 4 },
  { problem: '👩‍🚀👩‍🚀 + 👩‍🚀 =', answer: 3 },
  { problem: '👽 + 👽 + 👽 + 👽 =', answer: 4 },
  { problem: '👽 + 👽👽 + 👽👽 =', answer: 5 },
  { problem: '🤖🤖 + 🤖 + 🤖 =', answer: 4 },
  { problem: '🤖 + 🤖 + 🤖🤖 =', answer: 4 },
  { problem: '🤖🤖🤖 + 🤖 =', answer: 4 },
];

export default problemSet;
